version: '3.7'
services:
  mysql:
# https://github.com/docker-library/mysql/issues/302
# https://github.com/docker/for-win/issues/4824
    # image: mysql:8.0.17
    image: mysql:5.7.16
    networks:
      backend:
        aliases:
          - db
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./db:/var/lib/mysql
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=$$3cureUS
      # - MYSQL_DATABASE=db
      - MYSQL_DATABASE=deploy

  web:
    image: tp33/django
    networks:
      backend:
        aliases:
          - web
    depends_on:
      - mysql
    volumes:
      - ./app:/app
    ports:
      - "8001:8000"
    # command: bash -c "mod_wsgi-express start-server --working-directory /app/roadfoodr --reload-on-changes /app/roadfoodr/roadfoodr/wsgi.py"
    command: /app/init_script.bsh

networks:
  backend:
    driver: bridge
