# Generated by Django 2.2.6 on 2019-10-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rftrackr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roadfoods',
            new_name='Roadfood',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Visits',
            new_name='Visit',
        ),
    ]
