# Generated by Django 2.2.4 on 2019-10-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rftrackr', '0002_auto_20191017_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='id',
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
