# Generated by Django 2.2.4 on 2019-11-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rftrackr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadfood',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='roadfood',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
