# Generated by Django 2.2.4 on 2019-11-16 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rftrackr', '0002_auto_20191115_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date visited'),
        ),
    ]
